version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/AiAssistant.Api/Dockerfile
    ports:
      - "8080:8085"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Ollama__BaseUrl=http://ollama:11434
      - Qdrant__Host=qdrant
      - Qdrant__GrpcPort=6334
    depends_on:
      - ollama
      - qdrant

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  ollama_data:
  qdrant_data: 