services:
  api:
    build:
      context: .
      dockerfile: src/AiAssistant.Api/Dockerfile
    ports:
      - "8090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Ollama__BaseUrl=http://ollama:11434
      - Qdrant__Host=qdrant
      - Qdrant__GrpcPort=6334
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
      - OPENAI_MODEL=${OPENAI_MODEL}
    depends_on:
      - ollama
      - qdrant

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - OLLAMA_KEEP_ALIVE=-1

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
